domain_path: C:\Users\lrluc\Documents\Academia\hardwareDescription\examples\axiLite\axiLite_ide\hwp_axiLite\zynqmp_fsbl\zynqmp_fsbl_bsp
app_src_dir: C:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\zynqmp_fsbl
template: zynqmp_fsbl
